menus:
    HOME: /
    # ARCHIVE: /archives/
    GITHUB: https://github.com/meitufe
    # ABOUT: /about/

favicon: /favicon.png
logo: /images/logo.png
title: MEITU FE
description: ''
url: http://fe.meitu.com/
startyear: 2017
